### ISSUE TITLE
End of Line Bug/Request/Not sure?

### ISSUE THREAD

**Issue by nonplayer** [mike-ward/Markdown-Edit#233] opened 2017-01-26 18:02 UTC
Not sure how to title this one, but basically I'm noticing a number of wierdnesses with End of Line. In my case, I'm using Win10 Pro, if it matters.

In basic vanilla mode, the "End" key does not actually go to the end of a line, as would be expected. It only goes to immediately behind the last typed character. Any spaces or tabs are ignored. If I end a line with two spaces, the "End" key only sends the cursor to just after the last letter. Even more annoying is if I add those spaces and then hit End, it moves the cursor _forward_ to the closest letter. I would expect end End key to move to the end of the current line, no exceptions.

If I enable the visible line endings (\n), then the End key proceeds to function correctly, moving the cursor to just before the line ending notations. This happens regardless of extra spaces.

This appears to be a bug to me, as it is unlike any other editor I've used. Some editors do a "double end" function, where pressing End once moves to the last character, while pressing it twice moves to the actual end of line. Either of these implementations would be preferable to an End key that can't see the actual end of line at all.

Finally, a request for what would be a useful visual addition for future consideration. A bit of two-space highlighting would make it easier to visually note forced EOL structure in-line inside the editor, based on the standard:

```
When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return.
```

**Comment by mike-ward** [comment] 2017-01-26 19:02
Duplicate of #105

**Closed by mike-ward** 2017-01-26 19:02 UTC
