### ISSUE TITLE
auto-sync of edit and preview panes fails for block quotes in lists

### ISSUE THREAD

**Issue by EmperorXLII** [mike-ward/Markdown-Edit#176] opened 2016-08-14 15:56 UTC
The synchronization of the edit and preview panes appears to depend on lines only.  Adding lots of quotes (which take up more space in the preview pane), or tall images, breaks this.

**Comment by mike-ward** [comment] 2016-08-14 18:44
It doesn't work like that.

I'm closing this bug as an example of a poor bug report.

Issues should be specific, have steps to reproduce and if possible sample documents that demonstrate the issue.

**Comment by EmperorXLII** [comment] 2016-08-14 21:10
You're right; I had made an assumption without investigating properly.  It turned out to be harder to reproduce than I had thought.

Here is a file that shows what I was seeing (I think the bullets with quotes are the problematic elements).

[misaligned.txt](https://github.com/mike-ward/Markdown-Edit/files/417261/misaligned.txt)

**Comment by mike-ward** [comment] 2016-08-14 22:27
Looks like there may be an issue with block quotes. I'll look into it. Also, elements that have not height will cause issues (`<a name="anchor">`).

**Closed** 2016-09-01 12:54 UTC
Labels: bug, fixed
