### ISSUE TITLE
Fails when High Contrast Mode enabled (Alt+Shift+PrtScr)

### ISSUE THREAD

**Issue by veremenko-y** [mike-ward/Markdown-Edit#239] opened 2017-03-14 20:29 UTC
Is there any log available I can attach?

**Comment by mike-ward** [comment] 2017-03-15 12:34
Um..., just tried it here and it works. Might be something else. Does it crash or just not appear?

**Comment by veremenko-y** [comment] 2017-03-15 16:04
It crashed yesterday with "No responding" message from Windows. Tried again just now and got crash report. Hope it helps
![image](https://cloud.githubusercontent.com/assets/4127660/23958133/bae59a26-0966-11e7-84fc-716fd58420c6.png)

**Comment by cyotek** [comment] 2017-03-15 16:46
That's the exact same trace as the one I posted in #224, isn't that the one caused by trying to close MDE when the browser instance is unloaded?

**Comment by veremenko-y** [comment] 2017-03-15 16:48
@cyotek in my case it happens when I accidentally switch to high contrast mode

**Comment by cyotek** [comment] 2017-03-15 16:54
Yes, I didn't mean how you reproduce it, but rather how MDE (for whatever reason) thinks it needs to exit when it receives a notification that the browser has unloaded itself. Currently it seems to do that when RDC'ing to a client, you seem to have found another occurrence.

Incidentally, I can reproduce this scenario too - should I press <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>Print Screen</kbd>, MDE does the same sort of disappearing act I see with RDC.

**Comment by mike-ward** [comment] 2017-03-15 18:39
Does this happen when the preview is not visible? 

If I read this right, the browser is raising an unloaded event. I see I'm closing the app on that event. Don't remember why I'm doing that.

Of course, the larger question is why in the heck does the browser control unload on screen changes and why don't I see it on my system?

**Comment by cyotek** [comment] 2017-03-15 19:08
Yes, but *only* when I first toggle the setting. If I restart MDE afterwards, then it doesn't seem to crash - I assume because you haven't created the browser window when it's not needed.

As for why it's unloading, my guess is destroys and recreates itself in order to apply new flags. But that is entirely conjecture. It doesn't honour the theme you have in place for the browser (unless you have a high contrast theme and I never noticed), so it's perhaps a valid guess.

And for why it doesn't happen for you - haven't a clue :). Do you confirm the High Contrast dialog? It doesn't happen until you hit Yes and Windows re-themes itself.

**Comment by mike-ward** [comment] 2017-03-15 21:18
OK, I got it to happen on my home computer. Took out the browser unload handling. Seems to work fine. Can't remember why I put it in there in the first place.

**Closed** 2017-06-25 11:42 UTC
