### ISSUE TITLE
Markdown Files Saved to PDF don't expand equation markup

### ISSUE THREAD

**Issue by barriteau** [mike-ward/Markdown-Edit#202] opened 2016-10-15 10:13 UTC
Hi there,

File exported to html expands equation markup correctly, but when saved to pdf, equation markup doesn't work. Tested in two different pdf viewers, just in case. Many thanks.

![test](https://cloud.githubusercontent.com/assets/8275319/19409185/e36929e0-929c-11e6-9298-ca5fd4546165.jpg)

**Comment by mike-ward** [comment] 2016-10-15 10:44
Duplicate of #185

**Closed by mike-ward** 2016-10-15 10:44 UTC

**Comment by barriteau** [comment] 2016-10-15 10:57
My mistake, thanks a lot, I'll follow there :)

**Comment by mike-ward** [comment] 2016-10-15 13:39
No worries. Just keeping stuff in one place. The PDF feature is more popular than I thought. While I have a working solution at the moment the tiny font rendering for equations is still an issue.
